### ISSUE TITLE
[Bug] Last updated date on the map widget is curropted

### ISSUE THREAD

**Issue by galraij** [hasadna/anyway-newsflash-infographics#677]
Steps to reconstruct:
1. go to homepage
2. go to map card
3. download as image
4. open image locally on your machine and see date text is messed up:

![image](https://user-images.githubusercontent.com/11487010/120523611-c3cbc700-c3de-11eb-9497-d58d6e092eba.png)

![most_severe_accidents (15)](https://user-images.githubusercontent.com/3368312/119679728-42f25580-be49-11eb-947d-8240bab31870.png)

**Comment by daniel-ilan** [comment]
Technical problem description:
We use [html2canvas ](https://github.com/niklasvh/html2canvas) & [dom-to-image](https://github.com/tsayen/dom-to-image) packages for generating images from widgets. 
dom-to-image has better support for RTL but doesn't work with our canvases as they are ["tainted"](https://github.com/tsayen/dom-to-image#things-to-watch-out-for), for these we use html2canvas that has [issues](https://www.google.com/search?q=html2canvas+rtl+text+site%3Astackoverflow.com&newwindow=1&rlz=1C1CHBF_enIL925IL925&sxsrf=ALeKk00-N6VX3A8zQ6c4W13K70OpZCaD4w%3A1624115529672&ei=SQnOYLb6J_eH9u8Py5iuuAM&oq=html2canvas+rtl+&gs_lcp=Cgdnd3Mtd2l6EAEYATIECCMQJzIECCMQJzIGCAAQFhAeOgcIIxCwAxAnOgcIABBHELADOgcIABCwAxBDOgUIABDLAToCCAA6BwgAEIcCEBRQteMIWLXoCGDi_AhoAnACeACAAZcBiAGzBZIBAzAuNZgBAKABAaoBB2d3cy13aXrIAQrAAQE&sclient=gws-wiz) with RTL languages (especially with commas/hyphens etc.).

There are a number of possible solutions:

1. The one implemented on  #692  - render the text in SVG <text> tag. This has it's own issues as it requires positioning the text inside the SVG not with the normal HTML flow and might cause issues in future updates if the style changes.
2. Edit html2canvas manually to our needs. See [here](https://github.com/niklasvh/html2canvas/blob/2a013e20c814b7dbaea98f54f0bde8f553eb79a2/src/render/canvas/canvas-renderer.ts#L146), and [here](https://github.com/niklasvh/html2canvas/blob/7222aba1b42138c3d466525172411b3d9869095f/src/css/layout/text.ts#L69).
3. Because the issue with dom-to-image is with the canvas being "tainted" there is an option to get a temporary local copy of the canvas as an image and pass that image to dom-to-image function. 
4. There is a separate npm package [html-to-image](https://github.com/bubkoo/html-to-image) which is a fork from dom-to-image. It has the [same warning](https://github.com/bubkoo/html-to-image#things-to-watch-out-for) about "tainted" canvases but I tested it and it worked (locally) so it might still be an option worth looking at if there is a future issue with regarding this.
